stages:
  - build
  - deploy
  
cache:
  paths:
    - target/
  
build:
  stage: build
  tags:
    - maven
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/electricwires-**.jar
deploy:
  stage: deploy
  tags:
    - maven
  script:
    - mvn deploy
